"""empty message

Revision ID: 3a4ad2de8f9f
Revises: 89a66970b48e
Create Date: 2024-10-12 20:12:48.846459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4ad2de8f9f'
down_revision: Union[str, None] = '89a66970b48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchstory', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchstory', 'created_at')
    # ### end Alembic commands ###
