"""empty message

Revision ID: 89a66970b48e
Revises: b1bc367764fc
Create Date: 2024-10-12 19:07:09.102040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89a66970b48e'
down_revision: Union[str, None] = 'b1bc367764fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchstory', sa.Column('id_match', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'matchstory', 'matches', ['id_match'], ['id'], ondelete='CASCADE')
    op.drop_column('matchstory', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchstory', sa.Column('uuid', mysql.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'matchstory', type_='foreignkey')
    op.drop_column('matchstory', 'id_match')
    # ### end Alembic commands ###
