"""empty message

Revision ID: 9a8ab8d09a49
Revises: 037c2e3f398c
Create Date: 2024-10-11 23:57:26.861073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8ab8d09a49'
down_revision: Union[str, None] = '037c2e3f398c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('score', sa.JSON(), nullable=True))
    op.drop_column('matches', 'serialize_tennis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('serialize_tennis', sa.BLOB(), nullable=True))
    op.drop_column('matches', 'score')
    # ### end Alembic commands ###
