"""empty message

Revision ID: 037c2e3f398c
Revises: 9b3f947c4b10
Create Date: 2024-10-11 23:49:59.132962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '037c2e3f398c'
down_revision: Union[str, None] = '9b3f947c4b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('serialize_tennis', sa.LargeBinary(), nullable=True))
    op.drop_column('matches', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('score', mysql.JSON(), nullable=True))
    op.drop_column('matches', 'serialize_tennis')
    # ### end Alembic commands ###
